### PR TITLE
Subdivide `transact_block` stopwatch category

### PR DESCRIPTION
**Pull request by leoyvens**
In local tests, most time is spent in `apply_entity_modifications`. Dashboard PR https://github.com/graphprotocol/instrumentation/pull/2.

### CODE REVIEW

**Review by lutter — APPROVED** [review]
LGTM

**Comment by lutter** [comment]
Tests aren't compiling though

**Comment by leoyvens** [comment]
@lutter Fixed tests, and further divided between `insert` and `update` sections.

**Comment by leoyvens** [comment]
@lutter Could you give this another look?

**Comment by lutter** [comment]
Still looks good!

**Pull request merged**
