### PR TITLE
"count" aggregations fix 

### LINKED ISSUE #5634: [Bug] Single "count" aggregation fails
### Bug report

If I have a single "count" aggregation:
```
type Block @entity(timeseries: true) {
  id: Int8!
  timestamp: Timestamp!
  hash: Bytes!
  number: Int!
}

type Stats @aggregation(intervals: ["hour", "day"], source: "Block") {
  id: Int8!
  timestamp: Timestamp!

  count: Int! @aggregate(fn: "count")
}

```

graph-node fails with invalid SQL expression error:
```
postgres-defi    | 2024-09-07 20:45:32.788 UTC [91] ERROR:  syntax error at or near "from" at character 205
postgres-defi    | 2024-09-07 20:45:32.788 UTC [91] STATEMENT:  insert into "sgd1"."stats_hour"(id, timestamp, block$, "count") select max(id) as id, timestamp, $3, count(*) as "count" from (select id, date_bin('3600s', timestamp, 'epoch'::timestamptz) as timestamp,  from "sgd1"."block" where "sgd1"."block".timestamp >= $1 and "sgd1"."block".timestamp < $2 order by "sgd1"."block".timestamp) data group by timestamp
```
Note "," before "from" that shouldn't be there.

Subgraph example: https://github.com/YaroShkvorets/common-subgraphs/tree/main/aggregation-broken

### Relevant log output

_No response_

### IPFS hash

_No response_

### Subgraph name or link to explorer

_No response_

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

### PR DESCRIPTION
**Pull request by YaroShkvorets**
Fixes #5634 

- [x] fix extra comma
- [x] add test case
- [x] refactor sql query construction to avoid same bug in other cases

### CODE REVIEW

**Review by lutter — CHANGES_REQUESTED** [review]
Nice catch! It seems that with these changes `comma_sep` is always called with `first == false` and we could therefore get rid of that argument and simplify the code a little.

**Comment by YaroShkvorets** [comment]
Yes, I'll drop it.

**Comment by YaroShkvorets** [comment]
Should be good now.

**Review by lutter — APPROVED** [review]
Thanks for the PR!

**Comment by matthewdarwin** [comment]
@lutter can you merge it as well?  @YaroShkvorets doesn't have merge permissions.

**Comment by lutter** [comment]
> @lutter can you merge it as well? @YaroShkvorets doesn't have merge permissions.

Woops .. sorry, overlooked that. Merged now.

**Pull request merged**
