### PR TITLE
Refactor `SubgraphRunner` (old `InstanceManager`) - Part 2

### PR DESCRIPTION
**Pull request by evaporei**
This is a continuation of #3245.

Related issue #3246

This Pull Request tries to address two problems / solves two things:
- Make the whole `Runner` and it's member fields/structs more flat, easier to access and give more useful meaning in general to them;
- Divide the `run` code into three clear paths, each handling a `BlockStreamEvent` variant.

Here's a pseudocode that exemplifies the second part:

```rust
impl SubgraphRunner {
    fn run(mut self) -> Result<...> {
        loop {
            let stream = BlockStream::new(...);

            loop {
                let event = stream.next();

                match self.handle_stream_event(event) {
                    Action::Continue => continue,
                    Action::Stop => return Ok(()),
                    Action::Restart => break,
                };
            }
        }
    }

    fn handle_stream_event(event: BlockStreamEvent) -> Result<Action> {
        match event {
            Some(Ok(BlockStreamEvent::ProcessBlock(block, cursor))) =>
                self.handle_process_block(block, cursor),

            Some(Ok(BlockStreamEvent::Revert(revert_to_ptr, cursor))) => 
                self.handle_revert(revert_to_ptr, cursor),

            Some(Err(e)) => self.handle_err(e),

            None => unreachable!("The block stream stopped producing blocks"),
        }
    }
}

enum Action {
    Continue,
    Stop,
    Restart,
}

trait StreamEventHandler<C: Blockchain> {
    async fn handle_process_block(
        &mut self,
        block: BlockWithTriggers<C>,
        cursor: Option<String>,
    ) -> Result<Action, Error>;

    async fn handle_revert(
        &mut self,
        revert_to_ptr: BlockPtr,
        cursor: Option<String>,
    ) -> Result<Action, Error>;

    async fn handle_err(
        &mut self,
        err: CancelableError<Error>,
    ) -> Result<Action, Error>;
}

impl<C, T> StreamEventHandler<C> for SubgraphRunner<C, T>
where
    C: Blockchain,
    T: RuntimeHostBuilder<C>,
{
    async fn handle_process_block(
        &mut self,
        block: BlockWithTriggers<C>,
        cursor: Option<String>,
        cancel_handle: CancelHandle,
    ) -> Result<Action, Error> {
        // current branching that handles a block to be processed
    }

    async fn handle_revert(
        &mut self,
        subgraph_ptr: BlockPtr,
        revert_to_ptr: BlockPtr,
        cursor: Option<String>,
    ) -> Result<Action, Error> {
        // current branching that handles the revert
    }

    async fn handle_err(
        &mut self,
        err: CancelableError<Error>,
    ) -> Result<Action, Error> {
        // current branching that handles the error
    }
}
```

There's still work to be done in:

- Making the new `IndexingState` use methods instead of direct property access to its public fields, so that mutability is more controlled;
- Moving the new `trait` to another module;
- Extracting these methods from the `Runner`:
  - `process_block`;
  - `process_triggers`;
  - `create_dynamic_data_sources`;
  - `persist_dynamic_data_sources`;
- etc.

### CODE REVIEW

**Comment by leoyvens** [comment]
We should make sure to test this in the integration cluster before merging.

**Comment by otaviopace** [comment]
@leoyvens agreed 👍

**Review by mangas — APPROVED** [review]
This LGTM and is a good cleanup but we should still put this through integration just in case.

**Comment by evaporei** [comment]
Same POI results against `v0.25.2` on the integration cluster 🎉 

Thanks for the review guys! 😊 ❤️

**Pull request merged**
