### PR TITLE
Fix MacOS DNS issues on block ingestion

### PR DESCRIPTION
**Pull request by otaviopace**
This is being done because of DNS issues.

@VIVelev if you want to take a look as well since you were having the same issue 🙂

### CODE REVIEW

**Comment by maoueh** [comment]
I have some doubt about this to be honest. What is the actual error reported, is it `getaddrinfo EADDRINFO`?

I would aim much more at maximum open file descriptors limit being hit, which is by default super low on OS X system. I've been bitten by this just recently when the feature has been introduced, hence why I think it might be this.

It could be argue that it's still a reasonable fix to do, to lower support request but we should better understand the issue.

**Comment by leoyvens** [comment]
On my M1 this works fine. I agree with @maoueh that if it can be avoided by tuning the OS then I'd rather not merge this.

The ideal way to attempt to fix this would be to rebase our web3 fork on the latest upstream web3, which uses reqwest as a client which has connection caching so it should hopefully not run into these issues.

**Comment by otaviopace** [comment]
@leoyvens I remember searching about this and it doesn't seem to be a client related problem.

I will merge this then and we can investigate this further as @maoueh said so we can fix this on the source.

**Comment by maoueh** [comment]
What was the exact error shown, never got the details :)

**Comment by mangas** [comment]
```
error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known', node/src/chain.rs:107:25
```

**Pull request merged**
