### PR TITLE
runtime/wasm: add hosted abi encode/decode functions

### PR DESCRIPTION
**Pull request by jdkanani**
Related to https://github.com/graphprotocol/graph-node/issues/767

This PR will add support for `abi.encode` and `abi.decode` in hosted mapping functions. This can also be used to decode transaction data as mentioned by @fordN at https://github.com/graphprotocol/graph-node/issues/767 

Usage:

```ts
let encoded = abi.encode([
  ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(64)),
  ethereum.Value.fromAddress(Address.fromString("0x0000000000000000000000000000000000000420"))
])

// log.info("Encoded data {}", [encoded.toHexString()])

let decoded = abi.decode(["uint256", "address"], encoded)

// log.info("Decoded data {}", [decoded[0].toBigInt().toString()])
// log.info("Decoded data {}", [decoded[1].toAddress().toHexString()])
```

### CODE REVIEW

**Comment by Jannis** [comment]
@jdkanani I've been dreaming about someone contributing this for a long time! Thanks for the pull request 😄 

Regarding `abi.decode`: Isn't it limting to have only one flat array as the first argument? Considering that there are now deeply nested values (thanks to structs/tuples), I'm wondering if it wouldn't be better to have have something like

```ts
abi.decode("(uint256,address,(bytes32,int8,address))", [...values...])
```
where the types are passed in as a single string that is then parsed in Rust.

**Comment by jdkanani** [comment]
@Jannis For nested tuples/structs, it will be like this as per https://github.com/openethereum/ethabi:

```js
// For tuple (tested)
abi.decode(["uint256", "address", "(bytes32,uint256,address)"], [...values....])

// For tuple array (tested)
abi.decode(["uint256", "address", "(bytes32,uint256,address)[]"], [...values....])
```

**Comment by Jannis** [comment]
@jdkanani And that works with an arbitrary depth of tuples and arrays?

**Comment by jdkanani** [comment]
@Jannis Seems like `ethabi` or https://github.com/graphprotocol/ethabi doesn't support it for now.

Check here: https://github.com/openethereum/ethabi/pull/186 -- It could be fully-fledged PR to ethabi repo. 

It shouldn't affect this PR and this PR can be merged.

**Comment by jdkanani** [comment]
@Jannis quick question - does graph-node supports nested dynamic array/tuples?

**Comment by Jannis** [comment]
> @Jannis quick question - does graph-node support nested dynamic array/tuples?

Yes it does!

**Comment by Jannis** [comment]
I'm pretty sure our ethabi version supports arbitrary nesting.

**Comment by hilmarx** [comment]
hey, any updates on supporting `abi.encode` and `abi.decode`? Would be really helpful for me :)

**Comment by leoyvens** [comment]
@jdkanani are you still willing to work on this? We have an ethabi fork in which nested tuples should be supported, so I agree with @Jannis that the argument first argument should be a single type represented as a string. So instead of

```
abi.decode(["uint256", "address", "(bytes32,uint256,address)"], [...values....])
```

you'd have
```
abi.decode("(uint256,address,(bytes32,uint256,address))"], value)
```

We also need to add tests for this, ping me on Discord and I can give you pointers on how to add a test.

**Comment by leoyvens** [comment]
We're closing in favor of #2348 which was based on this, thanks!

**Pull request closed without merging**
