### PR TITLE
server: Fixed deploy suppressing error

### PR DESCRIPTION
**Pull request by That3Percent**
This PR fixes a regression that caused error messages to be suppressed when deploying a subgraph

### CODE REVIEW

**Comment by That3Percent** [comment]
Fixes #1544

**Review by Jannis — APPROVED** [review]
Good catch on the `map`/`map_ok`, that's very subtle...

**Comment by leoyvens** [comment]
Oops, thanks for fixing this! You need to `cargo fmt`.

**Comment by That3Percent** [comment]
I just did a significantly more involved refactor, which I don't normally do for a bugfix - but since the old futures api and styles are in some part responsible for the bug this seems warranted.

**Review by Jannis — APPROVED** [review]
Looks good!

**Pull request merged**
