### PR TITLE
Filipe/legacy event stream

### PR DESCRIPTION
**Pull request by mangas**

### CODE REVIEW

**Review by evaporei — APPROVED** [review]
LGTM, but I'm not sure someone else should double check this.

Also unit tests are failing.

**Review by That3Percent — APPROVED** [review]
LGTM as long as the issue with the tests was fixed.

**Comment by mangas** [comment]
Test failures were not related

**Comment by evaporei** [comment]
@mangas do you still have the failing build link? I'm worried we have non-deterministic tests 😕

**Pull request merged**
