### PR TITLE
store/postgres: warn if locale is not en_US.utf8

### LINKED ISSUE #3118: Mandate everything runs in some fixed locale `en_US.UTF8`
> We should mandate that everything runs in some fixed locale (maybe `en_US.UTF8`, though we'd need to look into if there are other locales that are more palatable to the non-English world) `graph-node` could then check on startup that its locale and the locale of the database are the expected one.

_Originally posted by @lutter in https://github.com/graphprotocol/graph-node/issues/1837#issuecomment-984160371_

### PR DESCRIPTION
**Pull request by saihaj**
Check for user's locale on startup and if it is not `en_US.utf8` panic.

Closes #3118

### CODE REVIEW

**Review by dotansimha — APPROVED** [review]

**Comment by leoyvens** [comment]
We need a guide for what an indexer should do when encountering this error, and the error message should link to that guide.

**Review by dotansimha — APPROVED** [review]

**Comment by azf20** [comment]
@saihaj from discussion with @leoyvens , I think we may want to make the error message a bit more informative (i.e. directing the user to change their DB locale to match, or change the env variable)

**Comment by lutter** [comment]
Here's how I think we should try and manage using the same locale for all indexers. We'll probably be stuck on `en_US.UTF-8` because there are fewer indexers that need to change, though `C` would be more preferable for performance.

1. Communicate a timeline and some writeup on what indexers need to do
1. Print a warning when the locale is not the specified one for a while (probably months, definitely two releases)
2. Switch to enforce the locale, i.e., the current behavior of panicking on startup

**Comment by saihaj** [comment]
https://github.com/graphprotocol/graph-node/pull/4163

**Pull request closed without merging**
