### PR TITLE
store: Disable collecting write metrics for synced deployments

### PR DESCRIPTION
**Pull request by lutter**
It's been a long-standing annoyance that the metrics for writing keep getting updated for synced subgraphs.

### CODE REVIEW

**Comment by leoyvens** [comment]
I think `deployment_synced` is only called once though, so if the graph node is restarted it won't be called again and the stopwatch will re-enable.

**Comment by lutter** [comment]
> I think `deployment_synced` is only called once though, so if the graph node is restarted it won't be called again and the stopwatch will re-enable.

It looks to me like `deployment_synced` is called once every time `graph-node` starts: that call is [here](https://github.com/graphprotocol/graph-node/blob/master/core/src/subgraph/runner.rs#L782-L803) and `self.state.synced` is initialized to `false` [here](https://github.com/graphprotocol/graph-node/blob/master/core/src/subgraph/runner.rs#L61) There are no other assignments to it.

**Comment by leoyvens** [comment]
Ah right, I assumed that was initialized from the DB.

**Review by leoyvens — APPROVED** [review]
Nice!

**Pull request merged**
