### PR TITLE
store: Quote table and column names when creating relational schema

### PR DESCRIPTION
**Pull request by lutter**
We make sure that the type and attribute names from GraphQL schemas are
safe to use in SQL, but users may use names that conflict with reserved
words in SQL; for example, a type 'User' will result in the creation of a
table 'user'. That causes a syntax error in Postgres, and we therefore need
to enclose these names in double-quotes during schema creation. Proper
queries do not have this problem since we have Diesel escape them as
identifiers already.

### CODE REVIEW

**Comment by lutter** [comment]
Note that this PR applies on top of #1178

**Comment by leoyvens** [comment]
Looks like the PR is not against master.

**Comment by lutter** [comment]
@leoyvens It was after merging #1178; it was just still marked as against the temporary branch

**Comment by leoyvens** [comment]
The diff is the same but it is necessary to change the base branch, right?

**Pull request merged**
