### PR TITLE
Rebase ethabi and web3 forks on upstream

### PR DESCRIPTION
**Pull request by leoyvens**
The web3 fork also includes this patch https://github.com/tomusdrw/rust-web3/pull/345 which allows doing calls by block hash, but we don't do so yet because of issues with support for EIP 1898 by Ethereum node providers.

This is as far as we can go on #400 for now.

### CODE REVIEW

**Comment by Jannis** [comment]
@leoyvens Wouldn't it be better to rebase our rust-web3 and ethabi `master` branches on top of upstream and then depend on these `master` branches instead of adding new branches?

**Comment by Jannis** [comment]
It also looks like this PR is accidentally removing `Cargo.lock`.

**Comment by leoyvens** [comment]
@Jannis I've updated the master branches. `Cargo.lock` is still there, it's just that these updates removed a bunch of transitive dependencies so the diff is very negative.

**Review by Jannis — APPROVED** [review]
Looks good to me. And yeah, 🤦 for thinking `Cargo.lock` was gone...

**Pull request merged**
