### PR TITLE
store: Properly initialize the subgraph block ptr on first start

### PR DESCRIPTION
**Pull request by lutter**

### CODE REVIEW

**Review by otaviopace — APPROVED** [review]
This solves https://github.com/graphprotocol/graph-node/issues/3370 right?

LGTM ✅

**Comment by lutter** [comment]
> This solves #3370 right?

It does - just updated the commit message to say that

**Comment by vincentho312** [comment]
@lutter Did you fix it?

**Comment by lutter** [comment]
> @lutter Did you fix it?

It's fixed, but not yet on the hosted service. The fix should be rolled out some time today.

**Pull request merged**
