### PR TITLE
delete 'shallow blocks' in block cache when not using firehose

### PR DESCRIPTION
**Pull request by sduchesneau**
* Should fix this: https://github.com/graphprotocol/graph-node/issues/4670
* And this: https://github.com/graphprotocol/graph-node/issues/4402

### CODE REVIEW

**Comment by incrypto32** [comment]
@leoyvens I tested it out locally , all the firehose blocks are getting deleted

**Comment by leoyvens** [comment]
@sduchesneau Thanks for raising the index issue. I think that's going to be a problem, to trigger a full scan of all the RPC block caches on startup. It is actually possible to write a migration that adds indexes to those tables, [see this example](https://github.com/graphprotocol/graph-node/tree/master/store/postgres/migrations/2022-03-09-07000_call_cache_block_number_idx).

**Comment by sduchesneau** [comment]
@leoyvens could you review now that I've incorporated your suggestion for indexes ?

**Review by leoyvens — APPROVED** [review]
Nice, I'll just make sure we run the migration ahead of time on hosted to avoid any hang up if the index creation turns out slower than expected.

**Comment by sduchesneau** [comment]
Let me know if there's anything pending or if you expect me to merge it ^_^

**Comment by incrypto32** [comment]
@sduchesneau its a code freeze currently, will merge it after next week

**Comment by paymog** [comment]
Any updates on this? We just had to disable a firehose and the manual process of deleting firehose ingested blocks is quite cumbersome

**Pull request merged**
