### PR TITLE
Remove the entry from `subgraph_features` table when a subgraph is removed

### PR DESCRIPTION
**Pull request by incrypto32**
Closes https://github.com/graphprotocol/graph-node/issues/4793

### CODE REVIEW

**Comment by lutter** [comment]
A better way to do that would be to have a foreign key constraint on `subgraph_features(id) references deployment_schemas(subgraph) on delete cascade` in the database. That way, Postgres will clean up.

Also, in the hosted service there are 40k entries in the `subgraph_features` table but only 28k entries in `deployment_schemas` - this change should therefore also come with a migration that removes unneeded entries before creating the fk constraint, something like (untested)
```
delete from subgraph_features f 
where not exists (select 1 from deployment_schemas ds where ds.subgraph = f.id)
```

It also seems that the `subgraph_features` table still needs to be documented in the [metadata docs](https://github.com/graphprotocol/graph-node/blob/master/docs/implementation/metadata.md)

**Comment by incrypto32** [comment]
> better way to do that would be to have a foreign key constraint on subgraph_features(id) references deployment_schemas(subgraph) on delete cascade

@lutter the `subgraph` column on `deployment_schemas` is not a unique field right so it wont be possible to create a fk constraint? Since same deployment_hash can be on different shards under different id its not possible to add a unique constraint too?

Would it be worth creating a postgres trigger instead ?

**Comment by incrypto32** [comment]
> it also seems that the subgraph_features table still needs to be documented in the metadata docs

I added the docs in [#4820](https://github.com/graphprotocol/graph-node/pull/4820)

**Review by lutter — APPROVED** [review]
Forget what I said about a fk constraint; you are right, since we don't have a unique index on `deployment_schemas.subgraph`, we can't do that here.

**Pull request merged**
