### PR TITLE
Adding unix cfg to ipc (unix-only) creation method 

### PR DESCRIPTION
**Pull request by georg-getz**

### CODE REVIEW

**Comment by leoyvens** [comment]
Lgtm but the git history is a mess, please squash this to a single commit.

**Comment by georg-getz** [comment]
> Lgtm but the git history is a mess, please squash this to a single commit.

I'm having some trouble with rebasing everything, can you use the squash and merge option please?

**Review by leoyvens — APPROVED** [review]

**Comment by leoyvens** [comment]
@georg-getz Github shows conflicts so I can't do that. You can use interactive rebase with `git rebase -i` to squash commits. O just make a new branch from a clean fork if you're having trouble getting your fork to be in sync with this repo.

**Comment by georg-getz** [comment]
@leoyvens ok I'm closing this PR and making the same one [here](https://github.com/graphprotocol/graph-node/pull/3081) minus the 40+ commits of couse. Also can you check [this](https://github.com/graphprotocol/rust-web3/pull/9) PR as well or should I write another DM to lutter about it?

**Pull request closed without merging**
