### PR TITLE
store: Fix call_cache queries when the chain is in a separate namespace

### PR DESCRIPTION
**Pull request by lutter**
Fixes https://github.com/graphprotocol/graph-node/issues/2168

### CODE REVIEW

**Comment by leoyvens** [comment]
For my understanding, how does this change make the code better handle a separate namespace?

**Comment by lutter** [comment]
> For my understanding, how does this change make the code better handle a separate namespace?

It doesn't improve anything, it just makes it work ;) Before the change, the queries were just incorrect when a chain had its own namespace.

**Comment by leoyvens** [comment]
@lutter I just wanted to understand how `"CURRENT_DATE > eth_call_meta.accessed_at"` is functionally different from

```
sql(&format!(
                            "CURRENT_DATE > {}.{}",
                            CallMetaTable::TABLE_NAME,
                            CallMetaTable::ACCESSED_AT
                        )),
```

**Comment by lutter** [comment]
> @lutter I just wanted to understand how `"CURRENT_DATE > eth_call_meta.accessed_at"` is functionally different from
> 
> ```rust
> sql(&format!(
>                             "CURRENT_DATE > {}.{}",
>                             CallMetaTable::TABLE_NAME,
>                             CallMetaTable::ACCESSED_AT
> )),
> ```

Aah .. now I understand the confusion: the original query had the wrong table name. `CallMetaTable::TABLE_NAME` boils down to `call_meta`, which is actually used in the query whereas `eth_call_meta` is not. Chains that live in their own namespace have tables `blocks`, `call_cache` and `call_meta` in their namespace that mirror `ethereum_block`, `eth_call_cache` and `eth_call_meta` in the public schema.

**Review by leoyvens — APPROVED** [review]

**Comment by leoyvens** [comment]
@lutter ah so we don't need to explicitly handle the namespace. Thanks for the clarification.

**Pull request merged**
